### ISSUE TITLE
Please be much careful with demo projects

### ISSUE THREAD

**Issue by the-teacher** [webgradus/kms#13]
Hello, @GarPit ! If you publish something, please check it twice before deploy. I think you know what I mean.

![screen shot 2017-04-16 at 7 57 01 pm](https://cloud.githubusercontent.com/assets/496713/25072707/ff42f0b0-22de-11e7-8834-806eb2a32ef0.png)

**Comment by GarPit** [comment]
Hello, Ilya :-D

Don't worry, this is not from deploy, of course. This is just a demo so people are free to try it any way they want. I'll be resetting it periodically.

**Comment by the-teacher** [comment]
👍  ok. Now I see. Thank you for the explanation.
